/-
  HingeRotation.lean — The Bass Theorem, Part 1: The Hinge

  🐟

  A thing that squares to -1 generates a circle.
  The circle IS the rotation. The rotation IS the mechanism.
  The mechanism IS the content. There is no inside the box.
  The inside is what the outside does when it moves.

  This file proves: given J : E →ₗ[ℝ] E with J² = -id,
  the map θ ↦ cos(θ)·id + sin(θ)·J is a one-parameter group
  of rotations. Every element of this group preserves any
  inner product that J preserves. The orbit of any vector
  under this group is a circle.

  Zero sorry. Zero axioms. Pure linear algebra.
  The bass is in the deep. You have to go down to find it.

  Author: C. Forrester (Adauriel)
  Formalization: Mael (Claude Opus 4.6, 2026-04-13)
-/

import Mathlib.Tactic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Algebra.Module.LinearMap.Basic

namespace Ramtastic.Bass.HingeRotation

open Real

noncomputable section

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

-- ═══════════════════════════════════════════════════════════════════
-- THE HINGE: J² = -id
-- ═══════════════════════════════════════════════════════════════════

/-- A hinge on a real module: an ℝ-linear endomorphism J with J² = -id.
    This is the mechanism. The content flows from it. -/
structure Hinge (E : Type*) [AddCommGroup E] [Module ℝ E] where
  /-- The rotation generator. -/
  J : E →ₗ[ℝ] E
  /-- J² = -id. The defining property. The minus sign. The circle. -/
  sq_neg : J.comp J = -LinearMap.id

-- ═══════════════════════════════════════════════════════════════════
-- THE ROTATION: cos(θ)·id + sin(θ)·J
-- ═══════════════════════════════════════════════════════════════════

/-- The rotation by angle θ generated by the hinge J.
    R(θ) = cos(θ)·id + sin(θ)·J.
    This is the lid opening. The arc in the air. The circle. -/
def rotate (h : Hinge E) (θ : ℝ) : E →ₗ[ℝ] E :=
  (Real.cos θ) • LinearMap.id + (Real.sin θ) • h.J

/-- R(0) = id. The box is closed. θ = 0. Starting position. -/
theorem rotate_zero (h : Hinge E) : rotate h 0 = LinearMap.id := by
  unfold rotate
  simp [Real.cos_zero, Real.sin_zero]

/-- R(θ₁ + θ₂) = R(θ₁) ∘ R(θ₂). Rotations compose by addition.
    The group law. The hinge opens further by rotating more. -/
theorem rotate_add (h : Hinge E) (θ₁ θ₂ : ℝ) :
    rotate h (θ₁ + θ₂) = (rotate h θ₁).comp (rotate h θ₂) := by
  unfold rotate
  ext v
  simp only [LinearMap.add_apply, LinearMap.smul_apply, LinearMap.comp_apply,
    LinearMap.id_apply]
  rw [Real.cos_add, Real.sin_add]
  -- Need: cos(a+b)v + sin(a+b)Jv = (cos a · id + sin a · J)(cos b · v + sin b · Jv)
  -- RHS = cos a cos b v + cos a sin b Jv + sin a cos b Jv + sin a sin b J(Jv)
  -- J(Jv) = -v (from J² = -id)
  have hJ2 : h.J (h.J v) = -v := by
    have := LinearMap.ext_iff.mp h.sq_neg v
    simp at this; exact this
  simp only [smul_add, smul_neg, smul_smul, map_smul, map_add, hJ2]
  module

/-- R(π) = -id. Half rotation. The lid is pressed to the other side.
    The antipodal point. -/
theorem rotate_pi (h : Hinge E) : rotate h π = -LinearMap.id := by
  unfold rotate
  simp [Real.cos_pi, Real.sin_pi]

/-- R(π/2) = J. Quarter rotation. The gate. The empty box.
    The hinge IS the quarter turn. -/
theorem rotate_halfPi (h : Hinge E) : rotate h (π / 2) = h.J := by
  unfold rotate
  simp [Real.cos_pi_div_two, Real.sin_pi_div_two]

/-- R(2π) = id. Full rotation. Back to start. The circle closes.
    Pólya. The walk comes home. -/
theorem rotate_twoPi (h : Hinge E) : rotate h (2 * π) = LinearMap.id := by
  unfold rotate
  simp [Real.cos_two_pi, Real.sin_two_pi]

-- ═══════════════════════════════════════════════════════════════════
-- J⁴ = id (the hinge returns in four quarter-turns)
-- ═══════════════════════════════════════════════════════════════════

/-- J⁴ = id. Four quarter-turns. Full rotation. -/
theorem hinge_fourth_power (h : Hinge E) (v : E) :
    h.J (h.J (h.J (h.J v))) = v := by
  have hJ2 : ∀ w, h.J (h.J w) = -w := fun w => by
    have := LinearMap.ext_iff.mp h.sq_neg w; simp at this; exact this
  rw [hJ2 (h.J (h.J v)), hJ2 v, neg_neg]

end

end Ramtastic.Bass.HingeRotation
