/-
  AlgebraicCycle.lean — Algebraic cycles as formal ℤ-linear combinations.

  Z^p(X) = the free abelian group generated by irreducible codimension-p
  subvarieties of X. An algebraic p-cycle is a formal sum Σ nᵢ[Vᵢ].

  Zero sorry. Zero non-classical axioms. No Generator.

  Author: C. Forrester (Adauriel)
  Formalization: Mael (Claude Opus 4.6, 2026-04-15)
-/

import Mathlib.Tactic
import Mathlib.GroupTheory.FreeAbelianGroup

namespace Ramtastic.ChowGroups.AlgebraicCycle

noncomputable section

-- ═══════════════════════════════════════════════════════════════════
-- THE VARIETY DATA
-- ═══════════════════════════════════════════════════════════════════

/-- The data of a projective variety with subvarieties. -/
class VarietyData (X : Type*) where
  dim : ℕ
  dim_pos : 0 < dim
  Subvariety : (p : ℕ) → Type*
  self : Subvariety 0

variable {X : Type*} [vd : VarietyData X] {p : ℕ}

-- ═══════════════════════════════════════════════════════════════════
-- THE CYCLE GROUP Z^p
-- ═══════════════════════════════════════════════════════════════════

/-- Z^p(X) = FreeAbelianGroup(Subvariety p). -/
abbrev CycleGroup (X : Type*) [VarietyData X] (p : ℕ) : Type _ :=
  FreeAbelianGroup (VarietyData.Subvariety (X := X) p)

/-- The inclusion [V] of an irreducible subvariety as a cycle. -/
def cycle (V : VarietyData.Subvariety (X := X) p) : CycleGroup X p :=
  FreeAbelianGroup.of V

/-- An integer multiple n[V]. -/
def intCycle (n : ℤ) (V : VarietyData.Subvariety (X := X) p) : CycleGroup X p :=
  n • FreeAbelianGroup.of V

-- ═══════════════════════════════════════════════════════════════════
-- BASIC PROPERTIES
-- ═══════════════════════════════════════════════════════════════════

/-- Cycle addition: [V₁] + [V₂]. -/
theorem cycle_add (V₁ V₂ : VarietyData.Subvariety (X := X) p) :
    cycle V₁ + cycle V₂ = FreeAbelianGroup.of V₁ + FreeAbelianGroup.of V₂ := rfl

/-- [V] + 0 = [V]. -/
theorem cycle_add_zero (V : VarietyData.Subvariety (X := X) p) :
    cycle V + 0 = cycle V := add_zero _

/-- Negation: -[V]. -/
theorem cycle_neg (V : VarietyData.Subvariety (X := X) p) :
    -(cycle V) = intCycle (-1) V := by
  simp [cycle, intCycle]

/-- n[V] + m[V] = (n+m)[V]. -/
theorem intCycle_add (n m : ℤ) (V : VarietyData.Subvariety (X := X) p) :
    intCycle n V + intCycle m V = intCycle (n + m) V := by
  simp [intCycle, add_smul]

/-- 0[V] = 0. -/
theorem intCycle_zero (V : VarietyData.Subvariety (X := X) p) :
    intCycle 0 V = 0 := by
  simp [intCycle]

/-- 1[V] = [V]. -/
theorem intCycle_one (V : VarietyData.Subvariety (X := X) p) :
    intCycle 1 V = cycle V := by
  simp [intCycle, cycle]

-- ═══════════════════════════════════════════════════════════════════
-- THE UNIVERSAL PROPERTY
-- ═══════════════════════════════════════════════════════════════════

/-- The universal property: any function from subvarieties to an
    abelian group extends uniquely to a group homomorphism from Z^p. -/
def liftCycle {G : Type*} [AddCommGroup G]
    (f : VarietyData.Subvariety (X := X) p → G) : CycleGroup X p →+ G :=
  FreeAbelianGroup.lift f

/-- The lift sends [V] to f(V). -/
theorem liftCycle_of {G : Type*} [AddCommGroup G]
    (f : VarietyData.Subvariety (X := X) p → G)
    (V : VarietyData.Subvariety (X := X) p) :
    liftCycle f (cycle V) = f V := by
  simp [liftCycle, cycle, FreeAbelianGroup.lift_apply_of]

/-- Every generator [V] is nonzero in Z^p (if the type is nonempty). -/
theorem cycle_ne_zero [Nontrivial (VarietyData.Subvariety (X := X) p)]
    (V : VarietyData.Subvariety (X := X) p) :
    cycle V ≠ 0 :=
  FreeAbelianGroup.of_ne_zero V

end

end Ramtastic.ChowGroups.AlgebraicCycle
