/-
  ProjectiveSpace.lean — CP^n: the concrete projective variety.

  A^*(CP^n) = ℤ[h]/(h^{n+1}).
  CycleGroup = FreeAbelianGroup Unit ≅ ℤ via coeff/fromZ.
  Intersection = integer multiplication of coefficients.

  TRUNCATION (2026-04-16): The relation h^{m+1} = 0 — i.e., A^p(CP^m) = 0 for p > m —
  is enforced via `RatEquivData.ratTrivial`. For p ≤ m: ratTrivial p = ⊥ (no extra
  equivalence; Chow^p ≅ ℤ generated by [h^p]). For p > m: ratTrivial p = ⊤
  (everything is rationally trivial; Chow^p = 0). This encodes that no irreducible
  subvariety of CP^m has codimension exceeding m.

  Zero sorry. Zero non-classical axioms. No Generator.

  Author: C. Forrester (Adauriel)
  Formalization: Mael (Claude Opus 4.6, 2026-04-15, truncation 2026-04-16)
-/

import Mathlib.Tactic
import Ramtastic.ChowGroups.IntersectionProduct

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option linter.unnecessarySimpa false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.flexible false
set_option linter.deprecated false

namespace Ramtastic.ChowGroups.ProjectiveSpace

open Ramtastic.ChowGroups.AlgebraicCycle
open Ramtastic.ChowGroups.RationalEquivalence
open Ramtastic.ChowGroups.ChowGroup
open Ramtastic.ChowGroups.IntersectionProduct

noncomputable section

/-- CP^n as a type. -/
def CPn (n : ℕ) : Type := Unit

-- ═══════════════════════════════════════════════════════════════════
-- FreeAbelianGroup Unit ≅ ℤ
-- ═══════════════════════════════════════════════════════════════════

def coeff : FreeAbelianGroup Unit →+ ℤ :=
  FreeAbelianGroup.lift (fun () => (1 : ℤ))

def fromZ (k : ℤ) : FreeAbelianGroup Unit :=
  k • FreeAbelianGroup.of ()

theorem coeff_fromZ (k : ℤ) : coeff (fromZ k) = k := by
  unfold fromZ coeff; rw [map_zsmul, FreeAbelianGroup.lift_apply_of]; simp

theorem fromZ_coeff (a : FreeAbelianGroup Unit) : fromZ (coeff a) = a := by
  induction a using FreeAbelianGroup.induction_on with
  | zero => simp [fromZ, coeff]
  | of u => cases u; simp [fromZ, coeff, FreeAbelianGroup.lift_apply_of]
  | neg u => cases u; simp [fromZ, coeff, FreeAbelianGroup.lift_apply_of, map_neg]
  | add a b ha hb => simp only [fromZ, map_add, add_smul] at *; rw [ha, hb]

theorem coeff_of : coeff (FreeAbelianGroup.of ()) = 1 :=
  FreeAbelianGroup.lift_apply_of _ _

def freeUnitEquivZ : FreeAbelianGroup Unit ≃+ ℤ where
  toFun := coeff; invFun := fromZ
  left_inv := fromZ_coeff; right_inv := coeff_fromZ
  map_add' := map_add coeff

-- ═══════════════════════════════════════════════════════════════════
-- BILINEAR MULTIPLICATION
-- ═══════════════════════════════════════════════════════════════════

def freeUnitMul (a b : FreeAbelianGroup Unit) : FreeAbelianGroup Unit :=
  fromZ (coeff a * coeff b)

theorem freeUnitMul_add_left (a b c : FreeAbelianGroup Unit) :
    freeUnitMul (a + b) c = freeUnitMul a c + freeUnitMul b c := by
  simp [freeUnitMul, fromZ, map_add, add_mul, add_smul]

theorem freeUnitMul_add_right (a b c : FreeAbelianGroup Unit) :
    freeUnitMul a (b + c) = freeUnitMul a b + freeUnitMul a c := by
  simp [freeUnitMul, fromZ, map_add, mul_add, add_smul]

theorem freeUnitMul_comm (a b : FreeAbelianGroup Unit) :
    freeUnitMul a b = freeUnitMul b a := by simp [freeUnitMul, mul_comm]

theorem freeUnitMul_assoc (a b c : FreeAbelianGroup Unit) :
    freeUnitMul (freeUnitMul a b) c = freeUnitMul a (freeUnitMul b c) := by
  simp [freeUnitMul, coeff_fromZ, mul_assoc]

theorem freeUnitMul_one_left (a : FreeAbelianGroup Unit) :
    freeUnitMul (FreeAbelianGroup.of ()) a = a := by
  simp [freeUnitMul, coeff_of, fromZ_coeff]

theorem freeUnitMul_one_right (a : FreeAbelianGroup Unit) :
    freeUnitMul a (FreeAbelianGroup.of ()) = a := by
  simp [freeUnitMul, coeff_of, fromZ_coeff]

theorem freeUnitMul_zero_left (a : FreeAbelianGroup Unit) :
    freeUnitMul 0 a = 0 := by simp [freeUnitMul, fromZ]

theorem freeUnitMul_zero_right (a : FreeAbelianGroup Unit) :
    freeUnitMul a 0 = 0 := by simp [freeUnitMul, fromZ]

-- ═══════════════════════════════════════════════════════════════════
-- CP^n INSTANCES
-- ═══════════════════════════════════════════════════════════════════

variable (m : ℕ) [hm : Fact (0 < m)]

instance cpnVD : VarietyData (CPn m) where
  dim := m; dim_pos := hm.out; Subvariety := fun _ => Unit; self := ()

/-- Rational equivalence on CP^m enforces the truncation A^p = 0 for p > m.
    For p ≤ m: ratTrivial = ⊥ (Chow^p ≅ ℤ).
    For p > m: ratTrivial = ⊤ (Chow^p = 0, encoding h^{m+1} = 0). -/
instance cpnRE : RatEquivData (CPn m) where
  ratTrivial := fun p => if p ≤ m then ⊥ else ⊤

/-- For p ≤ m, the rational equivalence subgroup is trivial. -/
theorem cpnRE_ratTrivial_of_le {p : ℕ} (hp : p ≤ m) :
    (cpnRE m).ratTrivial p = (⊥ : AddSubgroup (CycleGroup (CPn m) p)) := by
  show (if p ≤ m then ⊥ else ⊤ : AddSubgroup _) = ⊥
  exact if_pos hp

/-- For p > m, the rational equivalence subgroup is the full group (Chow = 0). -/
theorem cpnRE_ratTrivial_of_gt {p : ℕ} (hp : ¬ p ≤ m) :
    (cpnRE m).ratTrivial p = (⊤ : AddSubgroup (CycleGroup (CPn m) p)) := by
  show (if p ≤ m then ⊥ else ⊤ : AddSubgroup _) = ⊤
  exact if_neg hp

/-- Index HEq for chowClass on CP^m: the dependent type difference between
    `chowClass i a` and `chowClass j a` (when i = j and a has the same underlying
    representative) is bridgeable by HEq via index substitution. -/
private theorem cpn_chowClass_index_heq {p q : ℕ} (h : p = q)
    (a : CycleGroup (CPn m) p) (b : CycleGroup (CPn m) q)
    (h_ab : HEq a b) :
    HEq (chowClass (X := CPn m) p a) (chowClass (X := CPn m) q b) := by
  subst h
  cases h_ab
  rfl

private def cpnMul (p q : ℕ) (a : Chow (CPn m) p) (b : Chow (CPn m) q) :
    Chow (CPn m) (p + q) :=
  Quotient.liftOn₂ a b
    (fun a' b' => chowClass (p + q) (freeUnitMul a' b'))
    (fun a₁ b₁ a₂ b₂ ha hb => by
      -- Need: chowClass (p+q) (freeUnitMul a₁ b₁) = chowClass (p+q) (freeUnitMul a₂ b₂).
      -- Equivalent to: -(freeUnitMul a₁ b₁) + (freeUnitMul a₂ b₂) ∈ ratTrivial (p+q).
      -- Branch on whether p+q ≤ m.
      by_cases hpq : p + q ≤ m
      · -- p+q ≤ m: ratTrivial (p+q) = ⊥ requires equality. Then p, q ≤ m too,
        -- so a₁ = a₂ and b₁ = b₂ from their respective trivial relations.
        have hp : p ≤ m := by omega
        have hq : q ≤ m := by omega
        have h1 : a₁ = a₂ := by
          have h_rel := QuotientAddGroup.leftRel_apply.mp ha
          change -a₁ + a₂ ∈ (cpnRE m).ratTrivial p at h_rel
          rw [cpnRE_ratTrivial_of_le m hp] at h_rel
          change -a₁ + a₂ = 0 at h_rel
          exact neg_add_eq_zero.mp h_rel
        have h2 : b₁ = b₂ := by
          have h_rel := QuotientAddGroup.leftRel_apply.mp hb
          change -b₁ + b₂ ∈ (cpnRE m).ratTrivial q at h_rel
          rw [cpnRE_ratTrivial_of_le m hq] at h_rel
          change -b₁ + b₂ = 0 at h_rel
          exact neg_add_eq_zero.mp h_rel
        rw [h1, h2]
      · -- p+q > m: ratTrivial (p+q) = ⊤; everything is trivially equivalent.
        show chowClass (X := CPn m) (p+q) (freeUnitMul a₁ b₁) =
             chowClass (X := CPn m) (p+q) (freeUnitMul a₂ b₂)
        apply QuotientAddGroup.eq.mpr
        rw [cpnRE_ratTrivial_of_gt m hpq]
        exact AddSubgroup.mem_top _)

instance cpnInter : IntersectionData (CPn m) where
  inter := cpnMul m
  inter_add_left := fun p q a b c => by
    refine QuotientAddGroup.induction_on a fun a' => ?_
    refine QuotientAddGroup.induction_on b fun b' => ?_
    refine QuotientAddGroup.induction_on c fun c' => ?_
    show cpnMul m p q (↑(a' + b')) ↑c' = cpnMul m p q ↑a' ↑c' + cpnMul m p q ↑b' ↑c'
    simp only [cpnMul, Quotient.liftOn₂_mk]
    rw [freeUnitMul_add_left, map_add]
  inter_add_right := fun p q a b c => by
    refine QuotientAddGroup.induction_on a fun a' => ?_
    refine QuotientAddGroup.induction_on b fun b' => ?_
    refine QuotientAddGroup.induction_on c fun c' => ?_
    show cpnMul m p q ↑a' (↑(b' + c')) = cpnMul m p q ↑a' ↑b' + cpnMul m p q ↑a' ↑c'
    simp only [cpnMul, Quotient.liftOn₂_mk]
    rw [freeUnitMul_add_right, map_add]
  unit := chowClass 0 (FreeAbelianGroup.of ())
  inter_unit_left := fun p a => by
    refine QuotientAddGroup.induction_on a fun a' => ?_
    -- Goal: HEq (cpnMul m 0 p ⟦of()⟧ ⟦a'⟧) ⟦a'⟧
    -- After unfold: HEq (chowClass (0+p) (freeUnitMul (of()) a')) (chowClass p a')
    -- After freeUnitMul_one_left: HEq (chowClass (0+p) a') (chowClass p a')
    -- Bridge via Nat.zero_add p : 0 + p = p, with same underlying a' (Subvariety := Unit
    -- gives CycleGroup (CPn m) k = FreeAbelianGroup Unit defininitionally for all k).
    show HEq (cpnMul m 0 p ⟦FreeAbelianGroup.of ()⟧ ⟦a'⟧) ⟦a'⟧
    unfold cpnMul
    rw [Quotient.liftOn₂_mk, freeUnitMul_one_left]
    show HEq (chowClass (X := CPn m) (0 + p) a') (chowClass (X := CPn m) p a')
    exact cpn_chowClass_index_heq m (Nat.zero_add p) a' a' HEq.rfl
  inter_comm := fun p q a b => by
    refine QuotientAddGroup.induction_on a fun a' => ?_
    refine QuotientAddGroup.induction_on b fun b' => ?_
    -- Goal: HEq (cpnMul m p q ⟦a'⟧ ⟦b'⟧) (cpnMul m q p ⟦b'⟧ ⟦a'⟧)
    -- After unfold: HEq (chowClass (p+q) (fum a' b')) (chowClass (q+p) (fum b' a'))
    -- freeUnitMul_comm: fum a' b' = fum b' a'
    -- Then bridge HEq (chowClass (p+q) X) (chowClass (q+p) X) via Nat.add_comm.
    show HEq (cpnMul m p q ⟦a'⟧ ⟦b'⟧) (cpnMul m q p ⟦b'⟧ ⟦a'⟧)
    unfold cpnMul
    rw [Quotient.liftOn₂_mk, Quotient.liftOn₂_mk, freeUnitMul_comm a' b']
    exact cpn_chowClass_index_heq m (Nat.add_comm p q)
      (freeUnitMul b' a') (freeUnitMul b' a') HEq.rfl

end

end Ramtastic.ChowGroups.ProjectiveSpace
